version: "3.3"
services:
  redis:
    image: "redis:6.2-alpine"
    volumes:
      - redis_volume:/data

  web:
    image: magento2_web
    ports:
      - "80:80"
    links:
      - db
      - opensearch
      - redis
    depends_on:
      - db
      - opensearch
      - redis
    volumes:
      - /path/to/magento:/var/www/html


  db:
    image: mariadb:10.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db_volume:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    volumes:
      - opensearch_volume:/usr/share/opensearch/data

volumes:
  db_volume:
  redis_volume:
  opensearch_volume: